#!/bin/bash

#clear-test: Удаление файлов в каталоге $dir_name
dir_name=del
#dir_name=del1
#dir_name=

echo "preparing to delete files" >&2
if [[ -d $dir_name ]]; then
    if cd $dir_name; then
echo "deleting files" >&2
        echo rm * # ТЕСТИРОВАНИЕ
    else
        echo "cannot cd to '$dir_name'" >&2
        exit 1
    fi
else
    echo "no such directory: '$dir_name'" >&2
    exit 1
fi
echo "file deletion complete" >&2
exit # ТЕСТИРОВАНИЕ