#!/bin/bash

#clear-dir: Удаление файлов в каталоге $dir_name
dir_name=del

# cd $dir_name
# rm * неправильный вариант

if [[ ! -d "$dir_name" ]]; then
    echo "No such directory: '$dir_name'" >&2
    exit 1
fi
if ! cd "$dir_name"; then
    echo "Cannot cd to '$dir_name'" >&2
    exit 1
fi
if ! rm *; then
    echo "File deletion failed. Check results" >&2
    exit 1
fi
[[ -d "$dir_name" ]] && cd "$dir_name" && rm ./*