#!/bin/bash

# loan-calc : сценарий вычисления суммы 
# ежемесячных платежей по кредиту
PROGNAME="${0##*/}" # Для получения имени файла
# используется операция подстановки параметра

usage () {
cat <<- EOF
	Usage: $PROGNAME PRINCIPAL INTEREST MONTHS

	Where:

	PRINCIPAL is the amount of the loan.
	INTEREST is the APR as a number (7% = 0.07).
	MONTHS is the length of the loan's term.

	EOF
}

echo -n "Please enter principal -> "
read principal

echo -n "Please enter interest -> "
read interest

echo -n "Please enter number of months -> "
read months

# principal=$1
# interest=$2
# months=$3

# if (($# != 3)); then
# 	usage
# 	exit 1
# fi


printf "Total payment amount:\n"

bc <<- EOF
	scale = 10
	i = $interest / 12
	p = $principal
	n = $months
	a = p * ((i * ((1 + i) ^ n)) / (((1 + i) ^ n) - 1))
	print a, "\n"
EOF