#!/bin/bash

#чтение нескольких значений с клавиатуры
#read-integer

echo -n "Please enter one or more values -> "
read var1 var2 var3 var4 var5

echo "var1 = '$var1'"
echo "var2 = '$var2'"
echo "var3 = '$var3'"
echo "var4 = '$var4'"