#!/bin/bash

#проверка значения строки
test_string () {
    ANSWER=maybe

    if [ -z "$ANSWER" ]; then
            echo "There is no answer." >&2
            return 1
    fi
    if [ "$ANSWER" == "yes" ]; then
        echo "The answer is YES."
    elif [ "$ANSWER" == "no" ]; then
        echo "The answer is NO."
    elif [ "$ANSWER" == "maybe" ]; then
        echo "The answer is MAYBE."
    else
        echo "The answer is UNKNOWN."
    fi
}